### ISSUE TITLE
seowokim-todo

### ISSUE THREAD

**Issue by seo-wo** [ft-ts/backend#66]
- [x] cm 엔티티 변경해서 채팅마다 api 호출하지 않기
- [x] 유저 인포 가져올 때 친구 여부, 블락 여부 판단하기
- [x] 유저리스트에 있던 버튼들 프로필로 올려서 사용
- [ ] 상태관리 간소화( 최후의 방법으로 global context에 flag)
- [x] 채팅 인원수 삭제 -> channl list 갱신안할 수 있음
- [ ] noti 삭제할수도
